title: Programmieren lernen mit Python und Py5 # Replace this with your own book title
author: Michael Brenner

execute:
  execute_notebooks: "off" # Replace this if you want don't have notebooks with output and you want to add notebook output during build

only_build_toc_files: true # Replace this with false if you want to build all files in the book, allowing you to refer to pages which are not included in the table of contents

html:
  favicon: "figures/mbqw_favicon.ico" # Replace this with your own favicon
  baseurl: "https://mbqw.de" # Replace this with your own URL
  extra_css:
    - custom.css # steht in _static/custom.css (weil weiter unten html_static_path gesetzt wird

sphinx: # Options passed on to the underlying sphinx-parser
  config:
    language: de
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js # Required for live code: https://teachbooks.io/manual/features/live_code.html
      - https://cdn.jsdelivr.net/npm/single-question-quiz-element@latest/dist/single-question-quiz-element.umd.min.js
    thebe_config:
      use_thebe_lite: true # Required for live code: https://teachbooks.io/manual/features/live_code.html
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"] #exclude files which should not be accessible for live code: https://teachbooks.io/manual/features/live_code.html
    html_theme_options:
      logo:
        text: Programmieren lernen mit Python und Py5 # Replace this with your own book title
        image_light: mbqw_logo_white.gif # Put your logo for the light mode here (can be the same as image_dark)
        image_dark: mbqw_logo_black.gif # Put your logo for the dark mode here (can be the same as image_light)
      repository_url: "https://github.com/user/repo" # Add your own repo URL here
      path_to_docs: "book" # Required for edit_page_button, should be book if you're using TeachBooks package (https://github.com/TeachBooks/TeachBooks) or the TeachBooks deploy book workflow (https://teachbooks.io/manual/external/deploy-book-workflow/README.html)
      repository_branch: "main" # Replace when you change the name of your published branch (required for edit_page_button)
      use_edit_page_button: false # Replace with false if you don't want the edit page button (i.e. if you don't user to propose changes themselves or have a private repo)
      use_repository_button: false # Replace with false if you don't want the repository button (i.e. if you have a private repo)
      use_issues_button: false # Replace with false if you don't want the issues button (i.e. if you don't want to use GitHub issues or have a private repo)
      launch_buttons:
        thebe: true # Required for live code: https://teachbooks.io/manual/features/live_code.html
    tippy_add_class: "has-tippy"
    html_show_copyright: false # As the copyright is included in the author field
    html_last_updated_fmt: "%B %-d, %Y" # Adds the date of the last update to the footer
    html_static_path: ["_static", "figures"] # Add folder that contain files that need to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
          mtextInheritFont: true, # To typeset text within math prettier
        }
  extra_extensions: # Gives you a starter package of extensions to use in your book
    - jupyterbook_patches # Patches by TeachBooks https://github.com/TeachBooks/JupyterBook-Patches
    - download_link_replacer # Allows you to replace and add downloadable files to a page header https://teachbooks.io/manual/external/Download-Link-Replacer/README.html
    - sphinx_image_inverter # Inverts images for dark mode https://teachbooks.io/manual/external/Sphinx-Image-Inverter/README.html
    - sphinx_iframes # Eases the embedding of iframes https://teachbooks.io/manual/external/sphinx-iframes/README.html
    - sphinx_exercise # Allows you to add exercise boxes to your book https://ebp-sphinx-exercise.readthedocs.io/en/latest/
    - teachbooks_sphinx_tippy # Enables hoover over tips https://teachbooks.io/manual/external/teachbooks-sphinx-tippy/README.html
    - sphinx_named_colors # Allows you to use custom colors in your book https://teachbooks.io/manual/external/Sphinx-Named-Colors/README.html

bibtex_bibfiles:
  - references.bib # Required for references
